# _config.yml

# Site Settings
title: "REST API with Spring guide"
description: "Simple guide to help you on your web-dev journey"
baseurl: "/bookstoreAPI-spring-guide"
url: "https://keacluster.github.io"

# Build Settings

# Other settings...
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
