-- MySQL Script generated by MySQL Workbench
-- Tue Feb 20 14:39:21 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bookstore
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bookstore` ;

-- -----------------------------------------------------
-- Schema bookstore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bookstore` DEFAULT CHARACTER SET utf8 ;
USE `bookstore` ;

-- -----------------------------------------------------
-- Table `bookstore`.`Book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookstore`.`Book` ;

CREATE TABLE IF NOT EXISTS `bookstore`.`Book` (
  `idBook` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `author` VARCHAR(150) NOT NULL,
  `stock` INT ZEROFILL NOT NULL,
  `price` DOUBLE ZEROFILL NOT NULL,
  PRIMARY KEY (`idBook`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookstore`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookstore`.`User` ;

CREATE TABLE IF NOT EXISTS `bookstore`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookstore`.`Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookstore`.`Order` ;

CREATE TABLE IF NOT EXISTS `bookstore`.`Order` (
  `idOrder` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idOrder`),
  INDEX `fk_Order_User_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_Order_User`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `bookstore`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookstore`.`OrderDetail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookstore`.`OrderDetail` ;

CREATE TABLE IF NOT EXISTS `bookstore`.`OrderDetail` (
  `Order_idOrder` INT NOT NULL,
  `Book_idBook` INT NOT NULL,
  `quantity` INT NOT NULL,
  INDEX `fk_OrderDetail_Order1_idx` (`Order_idOrder` ASC) VISIBLE,
  INDEX `fk_OrderDetail_Book1_idx` (`Book_idBook` ASC) VISIBLE,
  CONSTRAINT `fk_OrderDetail_Order1`
    FOREIGN KEY (`Order_idOrder`)
    REFERENCES `bookstore`.`Order` (`idOrder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrderDetail_Book1`
    FOREIGN KEY (`Book_idBook`)
    REFERENCES `bookstore`.`Book` (`idBook`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
